import os
import sys
from operator import itemgetter
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import BaseMessage
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from langchain_community.vectorstores import FAISS
from utils.model_loader import ModelLoader
from exception.custom_exception import DocumentPortalException
from logger.custom_logger import CustomLogger
from prompt.prompt_library import PROMPT_REGISTRY
from model.models import PromptType
from typing import List, Optional



class ConversationalRAG:
    def __init__(self, session_id: str, retriever=None):
        try:
            self.log = CustomLogger().get_logger(__name__)
            self.session_id = session_id
            #self.retriever = retriever
            self.llm = self._load_llm()
            self.contextualize_prompt: ChatPromptTemplate = PROMPT_REGISTRY[PromptType.CONTEXTUALIZE_QUESTION.value]
            self.qa_prompt:ChatPromptTemplate = PROMPT_REGISTRY[PromptType.CONTEXT_QA.value]
            if retriever is None:
                raise ValueError("Retriever must be provided")
            self.retriever = retriever
            self._build_lcel_chain()
            self.log.info("ConversationalRAG initialized", session_id=session_id)
        except Exception as e:
            self.log.error("Error initializing ConversationalRAG", error=str(e))
            raise DocumentPortalException("Failed to initialize ConversationalRAG", sys)
        

    def load_retriever_from_faiss(self,index_path: str):
        """
        Load a FAISS vectorstore from disk and create a retriever.
        """
        try:
            embeddings = ModelLoader().load_embeddings()
            if not os.path.exists("index_path"):
                raise FileNotFoundError("FAISS index directory not found: {'index_path'}")
            vectorstore = FAISS.load_local(
                index_path,
                embeddings,
                allow_dangerous_deserialization=True,
            )
            self.retriever = vectorstore.as_retriever(search_type="similarity", search_kwargs={"k": 5})
            self.log.info("FAISS retriever loaded from disk", index_path="index_path", session_id=self.session_id)
            return self.retriever
        
        except Exception as e:
            self.log.error("Error loading FAISS retriever", error=str(e))
            raise DocumentPortalException("Failed to load FAISS retriever", sys)
        
    # def invoke(self, user_input: str, chat_history: Optional[List[BaseMessage]] = None) -> str:
    #     """
    #     Arguments:
    #         user_input: The user's question as a string.
    #         chat_history: Optional list of previous chat messages for context.
    #     """
    #     try:
    #         chat_history = chat_history or []
    #         payload = {"input": user_input, "chat_history": chat_history}
    #         answer = self.chain.invoke(payload)
    #         if not answer:
    #             self.log.warning("No answer generated by RAG chain", user_input=user_input, session_id=self.session_id)
    #         return "No answer generated."
            
    #         self.log.info("RAG chain invoked successfully",
    #             user_input=user_input,
    #             session_id=self.session_id,
    #             answer_preview=answer[:150],
    #         )
    #         return answer
            
    #     except Exception as e:
    #         self.log.error("Error invoking RAG chain", error=str(e))
    #         raise DocumentPortalException("Failed to invoke RAG chain", sys)
    
    def invoke(self, user_input: str, chat_history: Optional[List[BaseMessage]] = None) -> str:
        """
        Arguments:
        user_input: The user's question as a string.
        chat_history: Optional list of previous chat messages for context.
        """
        try:
            chat_history = chat_history or []
            payload = {"input": user_input, "chat_history": chat_history}
            answer = self.chain.invoke(payload)
            if not answer:
                self.log.warning(
                    "No answer generated by RAG chain",
                    user_input=user_input,
                    session_id=self.session_id
                )
                return "No answer generated."

            self.log.info(
                "RAG chain invoked successfully",
                user_input=user_input,
                session_id=self.session_id,
                answer_preview=answer[:150],
            )
            return answer

        except Exception as e:
            self.log.error("Error invoking RAG chain", error=str(e))
            raise DocumentPortalException("Failed to invoke RAG chain", sys)

    def _load_llm(self):
        try:
            llm = ModelLoader().load_llm()
            if not llm:
                raise ValueError("LLM could not be loaded")
            self.log.info("LLM loaded successfully", session_id=self.session_id)
            return llm
        except Exception as e:
            self.log.error("Error loading LLM", error=str(e))
            raise DocumentPortalException("Failed to load LLM", sys)
    
    
    @staticmethod
    def _format_docs(docs):
        return "\n\n".join(d.page_content for d in docs)

    def _build_lcel_chain(self):
        try:
            question_rewriter =(
                {"input": itemgetter("input"), "chat_history": itemgetter("chat_history")}
                | self.contextualize_prompt
                | self.llm
                | StrOutputParser()
            )
            retrieve_docs = question_rewriter | self.retriever | self._format_docs
            self.chain = (
                {
                    "context": retrieve_docs,
                    "input": itemgetter("input"),
                    "chat_history": itemgetter("chat_history")
                }
                |self.qa_prompt
                |self.llm
                |StrOutputParser()
            )    
            self.log.info("LCE chain built successfully", session_id=self.session_id)
        except Exception as e:
            self.log.error("Error building LCE chain", error=str(e), session_id=self.session_id)
            raise DocumentPortalException("Failed to build LCE chain", sys)
        
    
